@ContactFormApi_HostAddress = http://localhost:5068

GET {{ContactFormApi_HostAddress}}/weatherforecast/
Accept: application/json

###

		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.15" />